/*
 * runtime/runtime.c — NEXS Runtime Initialisation
 * =================================================
 * Provides nexs_runtime_init() and nexs_print_version() only.
 * Compiled into both the hosted interpreter AND standalone compiled binaries.
 * Does NOT contain main() — that lives in runtime/main.c (CLI) or in the
 * codegen-generated wrapper (compiled scripts).
 */

#include "nexs_alloc.h"
#include "nexs_common.h"
#include "nexs_value.h"
#include "nexs_hal.h"
#include "nexs_hal_module.h"
#include "nexs_eval.h"
#include "nexs_fn.h"
#include "nexs_registry.h"
#include "nexs_sys.h"
#include "nexs_runtime.h"

#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

#ifndef NEXS_BAREMETAL
#include <dirent.h>
#include <errno.h>
#endif

extern void builtins_register_all(void);
extern void ghal_register_builtins(void);

/* =========================================================
   VERSION
   ========================================================= */

#include "nexs_common.h"
#include "nexs_utils.h"
#include "nexs_value.h"

void nexs_print_version(FILE *out) {
  nexs_fprintf(
      out,
      "\033[1;36mNEXS\033[0m v%d.%d.%d — Buddy/Registry Runtime + Plan 9 "
      "Syscalls\n"
      "  Pool: %dKB  MinBlock: %dB  FnTable: %d slots\n"
      "  Syscalls: open create close read write seek stat pipe rfork exec\n"
      "  Inspired by: Thompson · Ritchie · Pike · Rashid\n\n",
      NEXS_VERSION_MAJOR, NEXS_VERSION_MINOR, NEXS_VERSION_PATCH,
      POOL_SIZE / 1024, MIN_BLOCK, MAX_FN_DEFS);
}

/* =========================================================
   AUTO-LOAD HELPERS
   ========================================================= */

#ifndef NEXS_BAREMETAL
static void load_directory_recursive(const char *dir_path) {
  DIR *d = opendir(dir_path);
  if (!d)
    return;
  struct dirent *ent;
  while ((ent = readdir(d)) != NULL) {
    if (ent->d_name[0] == '.')
      continue;
    char path[512];
    snprintf(path, sizeof(path), "%s/%s", dir_path, ent->d_name);

    struct stat st;
    if (stat(path, &st) == 0) {
      if (S_ISDIR(st.st_mode)) {
        load_directory_recursive(path);
      } else {
        size_t nlen = strlen(ent->d_name);
        if (nlen > 3 && strcmp(ent->d_name + nlen - 3, ".nx") == 0) {
          FILE *f = fopen(path, "r");
          if (f) {
            char buf[1024];
            size_t n = fread(buf, 1, sizeof(buf) - 1, f);
            buf[n] = '\0';
            fclose(f);
            
            const char *p = buf;
            while (*p && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r' || *p == '#')) {
              if (*p == '#') { while (*p && *p != '\n') p++; } else p++;
            }
            
            if (strncmp(p, "library", 7) == 0) {
              EvalCtx ctx;
              eval_ctx_init(&ctx);
              EvalResult r = eval_file(&ctx, path);
              val_free(&r.ret_val);
            }
          }
        }
      }
    }
  }
  closedir(d);
}
#endif

/* Weak declaration for the auto-load function generated by codegen */
__attribute__((weak)) void nexs_embed_load_all(EvalCtx *ctx) { (void)ctx; }

/* =========================================================
   RUNTIME INIT
   ========================================================= */

void nexs_runtime_init(void) {
  /* 1. Clear buddy pool and tree */
  memset(memory_pool, 0, POOL_SIZE);
  memset(buddy_tree, 0, sizeof(buddy_tree));
  g_array_count = 0;

  /* 2. Initialise fn_table */
  fn_table_init();

  /* 3. Initialise hierarchical registry */
  reg_init();

  /* 4. Initialise fd table (stdin/stdout/stderr) */
  sysio_init();

  /* 5. Register standard built-ins */
  builtins_register_all();

  /* 6. Register Plan 9 I/O built-ins */
  sysio_register_builtins();

  /* 7. Register Plan 9 process built-ins */
  sysproc_register_builtins();

  /* 8. Register HAL module builtins */
  hal_module_register_builtins();

  /* 9. Initialise HAL (UART, etc.) */
  nexs_hal_init();

  /* Register GHAL custom builtins and service modules */
  ghal_register_builtins();

  /* 10. Load embedded dependencies (if any) */
  EvalCtx ctx_emb;
  eval_ctx_init(&ctx_emb);
  nexs_embed_load_all(&ctx_emb);
}

void nexs_runtime_autoload(void) {
#ifndef NEXS_BAREMETAL
  /* 1. Load standard libraries and services from the base-nexs submodule first */
  load_directory_recursive("base-nexs/modules");
  load_directory_recursive("base-nexs/services");

  /* 2. Then load GHAL-specific overlay libraries and services */
  load_directory_recursive("modules");
  load_directory_recursive("services");
#endif
}
